"""
Model for templates (forms generated by inspectors).
"""
import uuid
from sqlalchemy import Column, String, Date, DateTime, Text, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from app.core.database import Base


class Template(Base):
    __tablename__ = "templates"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    # Template type: RI, CCT, or RPS
    template_type = Column(String(10), nullable=False, index=True)

    # Inspector who created it
    inspector_id = Column(
        UUID(as_uuid=True),
        ForeignKey("inspectores.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # Form data (flexible structure)
    form_data = Column(JSONB, nullable=False)

    # Generated Excel file
    file_url = Column(String(500), nullable=True)
    file_name = Column(String(255), nullable=True)

    # Review status
    status = Column(
        String(20),
        nullable=False,
        default="pending",
        index=True,
    )

    # Extracted fields for easier searching
    educational_site = Column(String(255), nullable=True, index=True)
    visit_date = Column(Date, nullable=True, index=True)

    # Admin review
    admin_notes = Column(Text, nullable=True)
    reviewed_by = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    reviewed_at = Column(DateTime(timezone=True), nullable=True)

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    # Relationships (to access inspector and reviewer from Python)
    inspector = relationship("Inspector", backref="templates")
    reviewer = relationship("User", backref="reviewed_templates")

    def __repr__(self):
        return f"<Template(type={self.template_type}, status={self.status})>"