"""
Script de prueba: genera un Excel RI con datos de ejemplo y lo guarda en disco.
Uso: python -m scripts.test_generador_ri
"""
from pathlib import Path
from app.services.excel_generator import RIGenerator


def main():
    # Datos de ejemplo simulando lo que vendría del formulario
    form_data = {
        "info_general": {
            "fecha_visita": "2026-05-21",
            "sede_educativa": "Jorge Eliécer Gaitán",
            "num_servicios": 325,
            "atiende_nombre": "María Rodríguez",
            "atiende_cargo": "Rectora",
            "realiza_nombre": "Camilo Durán",
            "realiza_cargo": "Inspector PAE",
        },
        "visita": {
        "opcion_1ra": "1ra visita X",
        "opcion_2da": "2da visita",
        "opcion_3ra": "3 visita",
        },
        "menu": {
            "descripcion_menu": "Pechuga a la plancha, pasta espagueti, monedas de plátano, verduras salteadas, jugo de piña",
            "intercambio_alimento": "N/A",
            "intercambio_motivo": "N/A",
            "intercambio_fecha": "N/A",
            "intercambio_autorizado_por": "N/A",
        },
        "calificaciones": {
            "item_1": "C",
            "item_2": "C",
            "item_3": "C",
            "item_4": "NC",
            "item_5": "C",
            "item_6": "C",
            "item_7": "C",
            "item_8": "N/A",
            "item_9": "C",
            "item_10": "C",
            "item_11": "C",
        },
        "observaciones": {
            "texto": "El servicio se prestó dentro de los horarios establecidos. Se observa cumplimiento adecuado de los protocolos.",
        },
        "firmas": {
            "firma1_nombre": "María Rodríguez",
            "firma1_documento": "1234567890",
            "firma1_cargo": "Rectora",
            "firma2_nombre": "Camilo Durán",
            "firma2_documento": "1098765432",
            "firma2_cargo": "Inspector PAE",
        },
    # ============ NUEVA: datos para hoja 2 ============
    "info_general_despacho": {
        "fecha_visita": "2026-05-21",
        "jornada_manana": "X",
        "jornada_tarde": "",
        "sede_educativa": "Jorge Eliécer Gaitán",
        "acceso_facil": "X",
        "acceso_dificil": "",
        "nombre_operador": "Productora de Alimentos PA",
        "num_contrato": "644/2026",
        "tipo_vehiculo": "Furgón refrigerado",
        "nombre_conductor": "Carlos Mendoza",
        "documento_conductor": "80123456",
        "placa_vehiculo": "TST 057",
        "atiende_nombre": "María Rodríguez",
        "atiende_cargo": "Rectora",
        "realiza_nombre": "Camilo Durán",
        "realiza_cargo": "Inspector PAE",
    },
    "calificaciones_despacho": {
        "item_1": "1",
        "item_2": "1",
        "item_3": "1",
        "item_4": "1",
        "item_5": "1",
        "item_6": "1",
        "item_7": "1",
        "item_8": "1",
        "item_9": "1",
        "item_10": "1",
        "item_11": "1",
        "item_12": "1",
        "item_13": "1",
        "item_14": "0",
        "item_15": "1",
        "item_16": "1",
        "item_17": "1",
        "item_18": "1",
    },
    "componentes": {
        "componente_1_nombre": "Pechuga de pollo",
        "componente_1_proveedor": "Avícola del Norte",
        "componente_1_fecha_fab": "2026-05-20",
        "componente_1_lote": "L20240520-01",
        "componente_1_fecha_venc": "2026-05-30",
        "componente_1_color": "Rosado claro",
        "componente_1_olor": "Fresco",
        "componente_1_sabor": "Normal",
        "componente_1_textura": "Firme",
        "componente_1_temp": "4°C",
        "componente_2_nombre": "Pasta espagueti",
        "componente_2_proveedor": "Pastas del Valle",
        "componente_2_fecha_fab": "2025-12-01",
        "componente_2_lote": "L20251201-03",
        "componente_2_fecha_venc": "2027-12-01",
        "componente_2_color": "Amarillo",
        "componente_2_olor": "Normal",
        "componente_2_sabor": "N/A",
        "componente_2_textura": "Seca",
        "componente_2_temp": "Ambiente",
        "componente_3_nombre": "Plátano maduro",
        "componente_3_proveedor": "Frutas Tropicales",
        "componente_3_fecha_fab": "N/A",
        "componente_3_lote": "N/A",
        "componente_3_fecha_venc": "N/A",
        "componente_3_color": "Amarillo",
        "componente_3_olor": "Dulce",
        "componente_3_sabor": "Dulce",
        "componente_3_textura": "Suave",
        "componente_3_temp": "Ambiente",
        "componente_4_nombre": "Jugo de piña",
        "componente_4_proveedor": "Jugos Naturales SA",
        "componente_4_fecha_fab": "2026-05-15",
        "componente_4_lote": "L20260515-02",
        "componente_4_fecha_venc": "2026-06-15",
        "componente_4_color": "Amarillo",
        "componente_4_olor": "Frutal",
        "componente_4_sabor": "Dulce",
        "componente_4_textura": "Líquida",
        "componente_4_temp": "8°C",
        "componente_5_nombre": "Verduras mixtas",
        "componente_5_proveedor": "Hortalizas del Campo",
        "componente_5_fecha_fab": "2026-05-21",
        "componente_5_lote": "N/A",
        "componente_5_fecha_venc": "2026-05-23",
        "componente_5_color": "Verde",
        "componente_5_olor": "Fresco",
        "componente_5_sabor": "Natural",
        "componente_5_textura": "Crujiente",
        "componente_5_temp": "6°C",
    },
    "observaciones_despacho": {
        "texto": "Vehículo en buen estado. Personal con todos los protocolos de bioseguridad. Temperaturas dentro del rango permitido.",
    },
    "firmas_despacho": {
        "firma1_nombre": "María Rodríguez",
        "firma1_documento": "1234567890",
        "firma1_cargo": "Rectora - Tel: 3101234567",
        "firma2_nombre": "Camilo Durán",
        "firma2_documento": "1098765432",
        "firma2_cargo": "Inspector PAE - Tel: 3209876543",
    },
    # ============ NUEVA: datos para hoja 3 ============
    "info_general_verificacion": {
        "fecha_visita": "2026-05-21",
        "jornada_manana": "X",
        "jornada_tarde": "",
        "operador": "Productora de Alimentos PA",
        "num_servicios": "325",
    },
    "productos": {
        # Producto 1
        "producto_1_fecha_recibido": "2026-05-20",
        "producto_1_nombre": "Pechuga de pollo",
        "producto_1_proveedor": "Avícola del Norte",
        "producto_1_fabricante": "Avícola del Norte SA",
        "producto_1_marca": "Pollo del Norte",
        "producto_1_fecha_venc": "2026-05-30",
        "producto_1_lote": "L20260520-01",
        "producto_1_fecha_suministro": "2026-05-21",
        "producto_1_textura": "Firme",
        "producto_1_color": "Rosado claro",
        "producto_1_olor": "Fresco",
        "producto_1_sabor": "Normal",
        "producto_1_apariencia": "Buena",
        "producto_1_peso_declarado": "150g",
        "producto_1_peso_verificado": "148g",
        "producto_1_cumplimiento_peso": "C",
        "producto_1_recep_mp_dia": "Lunes",
        "producto_1_recep_mp_temp": "4°C",
        "producto_1_recep_mp_cumpl": "C",
        "producto_1_almac_mp_dia": "Lunes",
        "producto_1_almac_mp_temp": "3°C",
        "producto_1_almac_mp_cumpl": "C",
        "producto_1_ensamble_dia": "Martes",
        "producto_1_ensamble_temp": "4°C",
        "producto_1_ensamble_cumpl": "C",
        "producto_1_despacho_dia": "Martes",
        "producto_1_despacho_temp": "4°C",
        "producto_1_despacho_cumpl": "C",
        # Producto 2
        "producto_2_fecha_recibido": "2026-05-19",
        "producto_2_nombre": "Pasta espagueti",
        "producto_2_proveedor": "Pastas del Valle",
        "producto_2_fabricante": "Molinos del Valle SA",
        "producto_2_marca": "Valle Dorado",
        "producto_2_fecha_venc": "2027-05-19",
        "producto_2_lote": "L20260515-04",
        "producto_2_fecha_suministro": "2026-05-21",
        "producto_2_textura": "Seca",
        "producto_2_color": "Amarillo",
        "producto_2_olor": "Normal",
        "producto_2_sabor": "N/A",
        "producto_2_apariencia": "Buena",
        "producto_2_peso_declarado": "500g",
        "producto_2_peso_verificado": "502g",
        "producto_2_cumplimiento_peso": "C",
        "producto_2_recep_mp_dia": "Lunes",
        "producto_2_recep_mp_temp": "Ambiente",
        "producto_2_recep_mp_cumpl": "C",
        "producto_2_almac_mp_dia": "Lunes",
        "producto_2_almac_mp_temp": "Ambiente",
        "producto_2_almac_mp_cumpl": "C",
        "producto_2_ensamble_dia": "Martes",
        "producto_2_ensamble_temp": "Ambiente",
        "producto_2_ensamble_cumpl": "C",
        "producto_2_despacho_dia": "Martes",
        "producto_2_despacho_temp": "Ambiente",
        "producto_2_despacho_cumpl": "C",
    },
    "observaciones_verificacion": {
        "obs_organolep": "Todos los productos presentan características organolépticas adecuadas.",
        "obs_gramajes_temp": "Gramajes verificados según especificaciones. Temperaturas dentro del rango.",
    },
    "firmas_verificacion": {
        "firma1_nombre": "María Rodríguez",
        "firma1_documento": "1234567890",
        "firma1_cargo": "Rectora",
        "firma2_nombre": "Camilo Durán",
        "firma2_documento": "1098765432",
        "firma2_cargo": "Inspector PAE",
    },
    # ============ NUEVA: datos para hoja 4 ============
    "info_general_rotulado": {
        "fecha_visita": "2026-05-21",
        "jornada_manana": "X",
        "jornada_tarde": "",
    },
    "productos_res5109": {
        # Producto 1
        "producto_1_nombre": "Pechuga de pollo",
        "producto_1_fecha_fab": "2026-05-20",
        "producto_1_fecha_venc": "2026-05-30",
        "producto_1_lote": "L20260520-01",
        "producto_1_nombre_alimento": "C",
        "producto_1_lista_ingredientes": "C",
        "producto_1_lote_verif": "C",
        "producto_1_contenido_neto": "C",
        "producto_1_fabricante_dir": "C",
        "producto_1_instruc_conserv": "C",
        "producto_1_fecha_venc_verif": "C",
        "producto_1_instruc_uso": "C",
        "producto_1_registro_sanitario": "C",
        "producto_1_empaque_primario": "C",
        "producto_1_tabla_nutricional": "C",
        "producto_1_cumplimiento": "C",
        # Producto 2
        "producto_2_nombre": "Pasta espagueti",
        "producto_2_fecha_fab": "2025-12-01",
        "producto_2_fecha_venc": "2027-12-01",
        "producto_2_lote": "L20251201-03",
        "producto_2_nombre_alimento": "C",
        "producto_2_lista_ingredientes": "C",
        "producto_2_lote_verif": "C",
        "producto_2_contenido_neto": "C",
        "producto_2_fabricante_dir": "C",
        "producto_2_instruc_conserv": "NC",
        "producto_2_fecha_venc_verif": "C",
        "producto_2_instruc_uso": "C",
        "producto_2_registro_sanitario": "C",
        "producto_2_empaque_primario": "C",
        "producto_2_tabla_nutricional": "C",
        "producto_2_cumplimiento": "C",
    },
    "productos_res333": {
        # Producto 1
        "producto_1_nombre": "Jugo de piña",
        "producto_1_fecha_fab": "2026-05-15",
        "producto_1_fecha_venc": "2026-06-15",
        "producto_1_lote": "L20260515-02",
        "producto_1_decl_nutrientes": "C",
        "producto_1_tamano_porciones": "C",
        "producto_1_medidas_caseras": "C",
        "producto_1_num_porciones": "C",
        "producto_1_equiv_medidas": "C",
        "producto_1_cumplimiento": "C",
        # Producto 2
        "producto_2_nombre": "Plátano maduro",
        "producto_2_fecha_fab": "N/A",
        "producto_2_fecha_venc": "N/A",
        "producto_2_lote": "N/A",
        "producto_2_decl_nutrientes": "N/A",
        "producto_2_tamano_porciones": "N/A",
        "producto_2_medidas_caseras": "N/A",
        "producto_2_num_porciones": "N/A",
        "producto_2_equiv_medidas": "N/A",
        "producto_2_cumplimiento": "N/A",
    },
    # ============ NUEVA: datos para hojas 5 y 6 ============
    "fotos_general": {
        "sede_educativa": "Jorge Eliécer Gaitán",
        "fecha": "2026-05-21",
        "periodo": "Mayo 2026",
        "foto_1": "app/templates_xlsx/imagenes_prueba/foto_prueba.jpg",
        "descripcion_1": "Vista general del comedor escolar",
        "foto_2": "app/templates_xlsx/imagenes_prueba/foto_prueba.jpg",
        "descripcion_2": "Área de preparación de alimentos",
    },
    "fotos_hallazgos": {
        "sede_educativa": "Jorge Eliécer Gaitán",
        "fecha": "2026-05-21",
        "periodo": "Mayo 2026",
        "foto_1": "app/templates_xlsx/imagenes_prueba/foto_prueba.jpg",
        "descripcion_1": "Hallazgo: refrigerador sin termómetro",
        "foto_2": "app/templates_xlsx/imagenes_prueba/foto_prueba.jpg",
        "descripcion_2": "Hallazgo: falta rotulado en contenedores",
    },
        
    }

    print("=" * 60)
    print("Generando planilla RI de prueba...")
    print("=" * 60)

    generator = RIGenerator()
    excel_bytes = generator.generate(form_data)

    # Guardar a disco para inspeccionar
    output_path = Path("scripts") / "salida_test_ri.xlsx"
    output_path.parent.mkdir(exist_ok=True)
    with open(output_path, "wb") as f:
        f.write(excel_bytes.getvalue())

    print(f"\n✓ Archivo generado: {output_path.resolve()}")
    print("\nÁbrelo con Excel para verificar que se rellenó correctamente.")


if __name__ == "__main__":
    main()