"""Crear tablas iniciales: users, inspectores, plantillas

Revision ID: 7e8f38de2136
Revises: 
Create Date: 2026-05-21 15:32:38.307328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e8f38de2136'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspectores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectores_codigo'), 'inspectores', ['codigo'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('plantillas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archivo_url', sa.String(length=500), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sede_educativa', sa.String(length=255), nullable=True),
    sa.Column('fecha_visita', sa.Date(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['inspectores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantillas_created_at'), 'plantillas', ['created_at'], unique=False)
    op.create_index(op.f('ix_plantillas_fecha_visita'), 'plantillas', ['fecha_visita'], unique=False)
    op.create_index(op.f('ix_plantillas_inspector_id'), 'plantillas', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_plantillas_sede_educativa'), 'plantillas', ['sede_educativa'], unique=False)
    op.create_index(op.f('ix_plantillas_status'), 'plantillas', ['status'], unique=False)
    op.create_index(op.f('ix_plantillas_tipo'), 'plantillas', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plantillas_tipo'), table_name='plantillas')
    op.drop_index(op.f('ix_plantillas_status'), table_name='plantillas')
    op.drop_index(op.f('ix_plantillas_sede_educativa'), table_name='plantillas')
    op.drop_index(op.f('ix_plantillas_inspector_id'), table_name='plantillas')
    op.drop_index(op.f('ix_plantillas_fecha_visita'), table_name='plantillas')
    op.drop_index(op.f('ix_plantillas_created_at'), table_name='plantillas')
    op.drop_table('plantillas')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_inspectores_codigo'), table_name='inspectores')
    op.drop_table('inspectores')
    # ### end Alembic commands ###
